repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        exclude: '.*\.(ipynb|gif)$'
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: ["--fix", "--output-format=github"]
        exclude: '.*\.ipynb$'
      - id: ruff-format
        exclude: '.*\.ipynb$'

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        name: format python code in documentation files
        additional_dependencies:
          - black==24.8.0

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-log-warn
