repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Stable version
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 23.7.0  # Latest stable version
    hooks:
      - id: black
        name: python code formatter
        language_version: python3

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0  # Corrected stable version for blacken-docs
    hooks:
      - id: blacken-docs
        name: format python code in documentation files
        additional_dependencies:
        - black==22.12.0

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Stable version for isort
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Correct version for flake8
    hooks:
      - id: flake8
        args: [--max-line-length=120]  # Consistent with Black's line length

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2  # Stable version for mypy
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-log-warn

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9  # Stable version for Bandit
    hooks:
      - id: bandit
        name: security-audit

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0  # Correct stable version for pydocstyle
    hooks:
      - id: pydocstyle
        name: enforce-docstring-format
        args: ["--convention=google"]
