site_name: pa-modeling
theme:
  name: material  # Use Material for MkDocs theme (optional)

site_author: Tobias Brock

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            render_typehint_in_signature: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - pamod: index.md
  - pamod.app: "reference/app.md"
  - pamod.benchmarking: 
      - Becnhmarker: "reference/benchmarking/benchmarker.md"
      - MultiBecnhmarker: "reference/benchmarking/multibenchmarker.md"
      - InputProcessor: "reference/benchmarking/processor.md"
  - pamod.data: 
      - StaticProcessEngine: "reference/data/staticengine.md"
      - ProcessDataHelper: "reference/data/datahelper.md"
      - ProcessedDataLoader: "reference/data/dataloader.md"
  - pamod.descriptives:
      - DescriptivesPlotter: "reference/descriptives/descriptives.md"
  - pamod.learner: 
      - Model: "reference/learner/model.md"
  - pamod.resampling: 
      - Resampler: "reference/resampling/resampler.md"
  - pamod.training:
      - brier_loss_multi: "reference/training/brier_multi.md"
      - get_probs: "reference/training/probs.md"
      - final_metrics: "reference/training/final_metrics.md"
      - MetricEvaluator: "reference/training/metrics.md"
      - MLPTrainer: "reference/training/mlptrainer.md"
      - Trainer: "reference/training/trainer.md"
  - pamod.tuning: 
      - BaseTuner: "reference/tuning/basetuner.md"
      - MetaTuner: "reference/tuning/metatuner.md"
      - HeboTuner: "reference/tuning/hebotuner.md"
      - RandomSearchTuner: "reference/tuning/rstuner.md"
