site_name: periodontal-modeling
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

site_author: Tobias Brock

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            render_typehint_in_signature: true
          selection:
            strict: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - periomod: index.md
  - periomod.app:
      - Overview: "reference/app/index.md"
      - App: "reference/app/app.md"
  - periomod.base:
      - Overview: "reference/base/index.md"
      - BaseConfig: "reference/base/baseconfig.md"
      - BaseValidator: "reference/base/basevalidator.md"
      - patient_to_df: "reference/base/patient_to_df.md"
      - Patient: "reference/base/patient.md"
      - Side: "reference/base/side.md"
      - Tooth: "reference/base/tooth.md"
  - periomod.benchmarking:
      - Overview: "reference/benchmarking/index.md"
      - Baseline: "reference/benchmarking/baseline.md"
      - BaseExperiment: "reference/benchmarking/baseexperiment.md"
      - Experiment: "reference/benchmarking/experiment.md"
      - BaseBenchmark: "reference/benchmarking/basebenchmark.md"
      - Benchmarker: "reference/benchmarking/benchmarker.md"
  - periomod.data:
      - Overview: "reference/data/index.md"
      - BaseLoader: "reference/data/baseloader.md"
      - BaseProcessor: "reference/data/baseprocessor.md"
      - StaticProcessEngine: "reference/data/staticengine.md"
      - ProcessDataHelper: "reference/data/datahelper.md"
      - BaseDataLoader: "reference/data/basedataloader.md"
      - ProcessedDataLoader: "reference/data/dataloader.md"
  - periomod.descriptives:
      - Overview: "reference/descriptives/index.md"
      - DescriptivesPlotter: "reference/descriptives/descriptives.md"
  - periomod.evaluation:
      - Overview: "reference/evaluation/index.md"
      - BaseModelEvaluator: "reference/evaluation/basemodelevaluator.md"
      - EvaluatorMethods: "reference/evaluation/evaluatormethods.md"
      - ModelEvaluator: "reference/evaluation/modelevaluator.md"
  - periomod.inference:
      - Overview: "reference/inference/index.md"
      - BaseModelInference: "reference/inference/basemodelinference.md"
      - ModelInference: "reference/inference/modelinference.md"
  - periomod.learner:
      - Overview: "reference/learner/index.md"
      - Model: "reference/learner/model.md"
  - periomod.resampling:
      - Overview: "reference/resampling/index.md"
      - BaseResampler: "reference/resampling/baseresampler.md"
      - Resampler: "reference/resampling/resampler.md"
  - periomod.training:
      - Overview: "reference/training/index.md"
      - brier_loss_multi: "reference/training/brier_multi.md"
      - get_probs: "reference/training/probs.md"
      - final_metrics: "reference/training/final_metrics.md"
      - BaseTrainer: "reference/training/basetrainer.md"
      - Trainer: "reference/training/trainer.md"
  - periomod.tuning:
      - Overview: "reference/tuning/index.md"
      - BaseTuner: "reference/tuning/basetuner.md"
      - HeboTuner: "reference/tuning/hebotuner.md"
      - RandomSearchTuner: "reference/tuning/rstuner.md"
  - periomod.wrapper:
      - Overview: "reference/wrapper/index.md"
      - BaseEvaluatorWrapper: "reference/wrapper/baseevaluatorwrapper.md"
      - BenchmarkWrapper: "reference/wrapper/benchmarkwrapper.md"
      - EvaluatorWrapper: "reference/wrapper/evaluatorwrapper.md"
      - load_benchmark: "reference/wrapper/loadbenchmark.md"
      - load_learners: "reference/wrapper/loadlearners.md"
      - ModelExtractor: "reference/wrapper/modelextractor.md"
